name: sqldebug
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nodecommander: ^0.1.0
  sqlcool: ^5.1.0
  wifi: ^0.1.5
